"""Implement dynamic workflow engine with UjiKompProgress

Revision ID: 0d1f52d2f07a
Revises: 75971d7ba3e2
Create Date: 2025-12-04 12:12:59.235473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d1f52d2f07a'
down_revision = '75971d7ba3e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_stages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workflow_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stage_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('content_config', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['stage_id'], ['workflow_stages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('uji_komp_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('user_response', sa.JSON(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('assessor_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['workflow_tasks.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['competency_tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competency_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_template_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('current_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'workflow_templates', ['workflow_template_id'], ['id'])
        batch_op.create_foreign_key(None, 'workflow_tasks', ['current_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competency_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('current_task_id')
        batch_op.drop_column('workflow_template_id')

    op.drop_table('uji_komp_progress')
    op.drop_table('workflow_tasks')
    op.drop_table('workflow_stages')
    op.drop_table('workflow_templates')
    # ### end Alembic commands ###
