"""Recreate competency_tests table standard english

Revision ID: 647f95655216
Revises: 96d1e3917e25
Create Date: 2025-12-03 11:49:26.381572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '647f95655216'
down_revision = '96d1e3917e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('impact_scenarios')
    op.drop_table('dependencies')
    op.drop_table('critical_assets')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('critical_assets',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_aset', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('tipe_aset', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('deskripsi', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='critical_assets_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dependencies',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('depends_on_asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['critical_assets.id'], name=op.f('dependencies_ibfk_1')),
    sa.ForeignKeyConstraint(['depends_on_asset_id'], ['critical_assets.id'], name=op.f('dependencies_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('impact_scenarios',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('nama_skenario', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('deskripsi', mysql.TEXT(), nullable=True),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('impact_scenarios_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
