"""Initial migration for MySQL

Revision ID: 7288706f084a
Revises: 
Create Date: 2025-12-02 15:27:17.117607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7288706f084a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('master_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_data_category'), ['category'], unique=False)

    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('regulations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filename', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_regulations_name'), ['name'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('nama_lengkap', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('limit_dasar', sa.Integer(), nullable=True),
    sa.Column('limit_madya', sa.Integer(), nullable=True),
    sa.Column('limit_template_peta', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('basic_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_unit_kerja', sa.String(length=200), nullable=False),
    sa.Column('nama_perusahaan', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('critical_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_aset', sa.String(length=200), nullable=False),
    sa.Column('tipe_aset', sa.String(length=100), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impact_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_skenario', sa.String(length=200), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_contexts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_context', sa.Text(), nullable=False),
    sa.Column('internal_context', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('basic_assessment_contexts',
    sa.Column('basic_assessment_id', sa.Integer(), nullable=False),
    sa.Column('organizational_context_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['basic_assessment_id'], ['basic_assessments.id'], ),
    sa.ForeignKeyConstraint(['organizational_context_id'], ['organizational_contexts.id'], ),
    sa.PrimaryKeyConstraint('basic_assessment_id', 'organizational_context_id')
    )
    op.create_table('basic_risk_identifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kode_risiko', sa.String(length=50), nullable=True),
    sa.Column('kategori_risiko', sa.String(length=100), nullable=False),
    sa.Column('unit_kerja', sa.String(length=200), nullable=False),
    sa.Column('sasaran', sa.Text(), nullable=True),
    sa.Column('tanggal_identifikasi', sa.Date(), nullable=False),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=False),
    sa.Column('akar_penyebab', sa.Text(), nullable=True),
    sa.Column('indikator_risiko', sa.Text(), nullable=True),
    sa.Column('internal_control', sa.Text(), nullable=True),
    sa.Column('deskripsi_dampak', sa.Text(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['basic_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_asset_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['critical_assets.id'], ),
    sa.ForeignKeyConstraint(['depends_on_asset_id'], ['critical_assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madya_assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama_asesmen', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('risk_map_template_id', sa.Integer(), nullable=True),
    sa.Column('structure_image_filename', sa.String(length=300), nullable=True),
    sa.Column('filter_organisasi', sa.String(length=200), nullable=True),
    sa.Column('filter_direktorat', sa.String(length=200), nullable=True),
    sa.Column('filter_divisi', sa.String(length=200), nullable=True),
    sa.Column('filter_departemen', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['risk_map_template_id'], ['risk_map_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_impact_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_level_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level_name', sa.String(length=100), nullable=False),
    sa.Column('color_hex', sa.String(length=7), nullable=False),
    sa.Column('min_score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_likelihood_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_map_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('likelihood_level', sa.Integer(), nullable=False),
    sa.Column('impact_level', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['risk_map_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basic_risk_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('risk_identification_id', sa.Integer(), nullable=False),
    sa.Column('probabilitas', sa.Integer(), nullable=True),
    sa.Column('dampak', sa.Integer(), nullable=True),
    sa.Column('probabilitas_kualitatif', sa.Float(), nullable=True),
    sa.Column('dampak_finansial', sa.Float(), nullable=True),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['basic_assessments.id'], ),
    sa.ForeignKeyConstraint(['risk_identification_id'], ['basic_risk_identifications.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('risk_identification_id')
    )
    op.create_table('madya_criteria_impact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('kriteriaDampak', sa.String(length=255), nullable=True),
    sa.Column('rangeFinansial', sa.Text(), nullable=True),
    sa.Column('deskripsiDampak1', sa.Text(), nullable=True),
    sa.Column('stra_dampak', sa.Text(), nullable=True),
    sa.Column('hukum_pelanggaran', sa.Text(), nullable=True),
    sa.Column('kepat_pelanggaran', sa.Text(), nullable=True),
    sa.Column('reput_keluhan', sa.Text(), nullable=True),
    sa.Column('reput_berita', sa.Text(), nullable=True),
    sa.Column('reput_saing', sa.Text(), nullable=True),
    sa.Column('sdm_keluhan', sa.Text(), nullable=True),
    sa.Column('sdm_turnover', sa.Text(), nullable=True),
    sa.Column('sdm_regretted_turnover', sa.Text(), nullable=True),
    sa.Column('sistem_gangguan', sa.Text(), nullable=True),
    sa.Column('sistem_siber', sa.Text(), nullable=True),
    sa.Column('sistem_platform', sa.Text(), nullable=True),
    sa.Column('ops_sla', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_1', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_2', sa.Text(), nullable=True),
    sa.Column('hsse_fatality_3', sa.Text(), nullable=True),
    sa.Column('hsse_kerusakan_lingkungan', sa.Text(), nullable=True),
    sa.Column('hsse_penurunan_esg', sa.Text(), nullable=True),
    sa.Column('pmn_tunda', sa.Text(), nullable=True),
    sa.Column('bank_fraud', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_rating', sa.Text(), nullable=True),
    sa.Column('asuransi_aset_peringkat', sa.Text(), nullable=True),
    sa.Column('aktu_rasio', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('madya_criteria_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=255), nullable=True),
    sa.Column('kemungkinan', sa.Text(), nullable=True),
    sa.Column('frekuensi', sa.Text(), nullable=True),
    sa.Column('persentase', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizational_structure_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('direktorat', sa.String(length=200), nullable=True),
    sa.Column('divisi', sa.String(length=200), nullable=True),
    sa.Column('unit_kerja', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sasaran_organisasi_kpi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sasaran_kpi', sa.Text(), nullable=False),
    sa.Column('target_level', sa.String(length=50), nullable=True),
    sa.Column('inherent_risk_score', sa.Integer(), nullable=True),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('risk_input_madya',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('sasaran_id', sa.Integer(), nullable=True),
    sa.Column('kode_risiko', sa.String(length=50), nullable=True),
    sa.Column('status_risiko', sa.String(length=50), nullable=True),
    sa.Column('peluang_ancaman', sa.String(length=50), nullable=True),
    sa.Column('kategori_risiko', sa.String(length=100), nullable=True),
    sa.Column('kategori_risiko_lainnya', sa.String(length=200), nullable=True),
    sa.Column('unit_kerja', sa.String(length=200), nullable=True),
    sa.Column('tanggal_identifikasi', sa.Date(), nullable=True),
    sa.Column('deskripsi_risiko', sa.Text(), nullable=True),
    sa.Column('akar_penyebab', sa.Text(), nullable=True),
    sa.Column('indikator_risiko', sa.Text(), nullable=True),
    sa.Column('internal_control', sa.Text(), nullable=True),
    sa.Column('deskripsi_dampak', sa.Text(), nullable=True),
    sa.Column('inherent_probabilitas', sa.Integer(), nullable=True),
    sa.Column('inherent_dampak', sa.Integer(), nullable=True),
    sa.Column('inherent_skor', sa.Integer(), nullable=True),
    sa.Column('inherent_prob_kualitatif', sa.Float(), nullable=True),
    sa.Column('inherent_dampak_finansial', sa.Float(), nullable=True),
    sa.Column('inherent_nilai_bersih', sa.Float(), nullable=True),
    sa.Column('pemilik_risiko', sa.String(length=150), nullable=True),
    sa.Column('jabatan_pemilik', sa.String(length=150), nullable=True),
    sa.Column('kontak_pemilik_hp', sa.String(length=50), nullable=True),
    sa.Column('kontak_pemilik_email', sa.String(length=120), nullable=True),
    sa.Column('strategi', sa.String(length=100), nullable=True),
    sa.Column('rencana_penanganan', sa.Text(), nullable=True),
    sa.Column('biaya_penanganan', sa.Float(), nullable=True),
    sa.Column('penanganan_dilakukan', sa.Text(), nullable=True),
    sa.Column('status_penanganan', sa.String(length=50), nullable=True),
    sa.Column('jadwal_mulai_penanganan', sa.Date(), nullable=True),
    sa.Column('jadwal_selesai_penanganan', sa.Date(), nullable=True),
    sa.Column('pic_penanganan', sa.String(length=150), nullable=True),
    sa.Column('residual_probabilitas', sa.Integer(), nullable=True),
    sa.Column('residual_dampak', sa.Integer(), nullable=True),
    sa.Column('residual_skor', sa.Integer(), nullable=True),
    sa.Column('residual_prob_kualitatif', sa.Float(), nullable=True),
    sa.Column('residual_dampak_finansial', sa.Float(), nullable=True),
    sa.Column('residual_nilai_bersih', sa.Float(), nullable=True),
    sa.Column('tanggal_review', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['madya_assessments.id'], ),
    sa.ForeignKeyConstraint(['sasaran_id'], ['sasaran_organisasi_kpi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('risk_input_madya')
    op.drop_table('sasaran_organisasi_kpi')
    op.drop_table('organizational_structure_entries')
    op.drop_table('madya_criteria_probability')
    op.drop_table('madya_criteria_impact')
    op.drop_table('basic_risk_analysis')
    op.drop_table('risk_map_scores')
    op.drop_table('risk_map_likelihood_labels')
    op.drop_table('risk_map_level_definitions')
    op.drop_table('risk_map_impact_labels')
    op.drop_table('madya_assessments')
    op.drop_table('dependencies')
    op.drop_table('basic_risk_identifications')
    op.drop_table('basic_assessment_contexts')
    op.drop_table('user_roles')
    op.drop_table('risk_map_templates')
    op.drop_table('organizational_contexts')
    op.drop_table('impact_scenarios')
    op.drop_table('critical_assets')
    op.drop_table('basic_assessments')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    with op.batch_alter_table('regulations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_regulations_name'))

    op.drop_table('regulations')
    op.drop_table('permissions')
    with op.batch_alter_table('master_data', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_data_category'))

    op.drop_table('master_data')
    op.drop_table('departments')
    # ### end Alembic commands ###
