"""Expand standard_type length in competency_units

Revision ID: 75971d7ba3e2
Revises: d73f963d941b
Create Date: 2025-12-03 13:24:23.074750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '75971d7ba3e2'
down_revision = 'd73f963d941b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competency_units', schema=None) as batch_op:
        batch_op.alter_column('standard_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competency_units', schema=None) as batch_op:
        batch_op.alter_column('standard_type',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
