"""Refactor Scheme to Job Groups structure

Revision ID: 8836c17459a8
Revises: 0d1f52d2f07a
Create Date: 2025-12-05 15:53:09.223625

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8836c17459a8'
down_revision = '0d1f52d2f07a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_job_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['certification_schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['job_group_id'], ['scheme_job_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheme_job_group_units',
    sa.Column('job_group_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_group_id'], ['scheme_job_groups.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['competency_units.id'], ),
    sa.PrimaryKeyConstraint('job_group_id', 'unit_id')
    )
    op.drop_table('scheme_units')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheme_units',
    sa.Column('scheme_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('unit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['certification_schemes.id'], name=op.f('scheme_units_ibfk_1')),
    sa.ForeignKeyConstraint(['unit_id'], ['competency_units.id'], name=op.f('scheme_units_ibfk_2')),
    sa.PrimaryKeyConstraint('scheme_id', 'unit_id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('scheme_job_group_units')
    op.drop_table('scheme_evidences')
    op.drop_table('scheme_job_groups')
    # ### end Alembic commands ###
