"""Ubah tipe data float ke numeric untuk keuangan

Revision ID: 96d1e3917e25
Revises: 7288706f084a
Create Date: 2025-12-02 18:09:32.696189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '96d1e3917e25'
down_revision = '7288706f084a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('basic_risk_analysis', schema=None) as batch_op:
        batch_op.alter_column('probabilitas_kualitatif',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('dampak_finansial',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('risk_input_madya', schema=None) as batch_op:
        batch_op.alter_column('inherent_prob_kualitatif',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('inherent_dampak_finansial',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
        batch_op.alter_column('inherent_nilai_bersih',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
        batch_op.alter_column('biaya_penanganan',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
        batch_op.alter_column('residual_prob_kualitatif',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=5, scale=2),
               existing_nullable=True)
        batch_op.alter_column('residual_dampak_finansial',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)
        batch_op.alter_column('residual_nilai_bersih',
               existing_type=mysql.FLOAT(),
               type_=sa.Numeric(precision=20, scale=2),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('risk_input_madya', schema=None) as batch_op:
        batch_op.alter_column('residual_nilai_bersih',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('residual_dampak_finansial',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('residual_prob_kualitatif',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('biaya_penanganan',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('inherent_nilai_bersih',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('inherent_dampak_finansial',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('inherent_prob_kualitatif',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('basic_risk_analysis', schema=None) as batch_op:
        batch_op.alter_column('dampak_finansial',
               existing_type=sa.Numeric(precision=20, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('probabilitas_kualitatif',
               existing_type=sa.Numeric(precision=5, scale=2),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
