"""Add competency master tables and scheme relation

Revision ID: d73f963d941b
Revises: a95a1fd5852c
Create Date: 2025-12-03 12:44:43.490150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd73f963d941b'
down_revision = 'a95a1fd5852c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('certification_schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('competency_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('standard_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('scheme_units',
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['scheme_id'], ['certification_schemes.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['competency_units.id'], ),
    sa.PrimaryKeyConstraint('scheme_id', 'unit_id')
    )
    with op.batch_alter_table('competency_tests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scheme_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'certification_schemes', ['scheme_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competency_tests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('scheme_id')

    op.drop_table('scheme_units')
    op.drop_table('competency_units')
    op.drop_table('certification_schemes')
    # ### end Alembic commands ###
